using ImGuiNET;
using Raylib_cs;

namespace CreepyUtil.BackBone;

internal static class ImguiKeyMapping
{
    public static readonly IReadOnlyDictionary<ImGuiMouseCursor, MouseCursor> MouseCursorMap =
        new Dictionary<ImGuiMouseCursor, MouseCursor>
        {
            [ImGuiMouseCursor.Arrow] = MouseCursor.Arrow,
            [ImGuiMouseCursor.TextInput] = MouseCursor.IBeam,
            [ImGuiMouseCursor.Hand] = MouseCursor.PointingHand,
            [ImGuiMouseCursor.ResizeAll] = MouseCursor.ResizeAll,
            [ImGuiMouseCursor.ResizeEW] = MouseCursor.ResizeEw,
            [ImGuiMouseCursor.ResizeNESW] = MouseCursor.ResizeNesw,
            [ImGuiMouseCursor.ResizeNS] = MouseCursor.ResizeNs,
            [ImGuiMouseCursor.ResizeNWSE] = MouseCursor.ResizeNwse,
            [ImGuiMouseCursor.NotAllowed] = MouseCursor.NotAllowed
        };

    public static readonly IReadOnlyDictionary<KeyboardKey, ImGuiKey> RaylibKeyMap =
        new Dictionary<KeyboardKey, ImGuiKey>
        {
            [KeyboardKey.Apostrophe] = ImGuiKey.Apostrophe,
            [KeyboardKey.Comma] = ImGuiKey.Comma,
            [KeyboardKey.Minus] = ImGuiKey.Minus,
            [KeyboardKey.Period] = ImGuiKey.Period,
            [KeyboardKey.Slash] = ImGuiKey.Slash,
            [KeyboardKey.Zero] = ImGuiKey._0,
            [KeyboardKey.One] = ImGuiKey._1,
            [KeyboardKey.Two] = ImGuiKey._2,
            [KeyboardKey.Three] = ImGuiKey._3,
            [KeyboardKey.Four] = ImGuiKey._4,
            [KeyboardKey.Five] = ImGuiKey._5,
            [KeyboardKey.Six] = ImGuiKey._6,
            [KeyboardKey.Seven] = ImGuiKey._7,
            [KeyboardKey.Eight] = ImGuiKey._8,
            [KeyboardKey.Nine] = ImGuiKey._9,
            [KeyboardKey.Semicolon] = ImGuiKey.Semicolon,
            [KeyboardKey.Equal] = ImGuiKey.Equal,
            [KeyboardKey.A] = ImGuiKey.A,
            [KeyboardKey.B] = ImGuiKey.B,
            [KeyboardKey.C] = ImGuiKey.C,
            [KeyboardKey.D] = ImGuiKey.D,
            [KeyboardKey.E] = ImGuiKey.E,
            [KeyboardKey.F] = ImGuiKey.F,
            [KeyboardKey.G] = ImGuiKey.G,
            [KeyboardKey.H] = ImGuiKey.H,
            [KeyboardKey.I] = ImGuiKey.I,
            [KeyboardKey.J] = ImGuiKey.J,
            [KeyboardKey.K] = ImGuiKey.K,
            [KeyboardKey.L] = ImGuiKey.L,
            [KeyboardKey.M] = ImGuiKey.M,
            [KeyboardKey.N] = ImGuiKey.N,
            [KeyboardKey.O] = ImGuiKey.O,
            [KeyboardKey.P] = ImGuiKey.P,
            [KeyboardKey.Q] = ImGuiKey.Q,
            [KeyboardKey.R] = ImGuiKey.R,
            [KeyboardKey.S] = ImGuiKey.S,
            [KeyboardKey.T] = ImGuiKey.T,
            [KeyboardKey.U] = ImGuiKey.U,
            [KeyboardKey.V] = ImGuiKey.V,
            [KeyboardKey.W] = ImGuiKey.W,
            [KeyboardKey.X] = ImGuiKey.X,
            [KeyboardKey.Y] = ImGuiKey.Y,
            [KeyboardKey.Z] = ImGuiKey.Z,
            [KeyboardKey.Space] = ImGuiKey.Space,
            [KeyboardKey.Escape] = ImGuiKey.Escape,
            [KeyboardKey.Enter] = ImGuiKey.Enter,
            [KeyboardKey.Tab] = ImGuiKey.Tab,
            [KeyboardKey.Backspace] = ImGuiKey.Backspace,
            [KeyboardKey.Insert] = ImGuiKey.Insert,
            [KeyboardKey.Delete] = ImGuiKey.Delete,
            [KeyboardKey.Right] = ImGuiKey.RightArrow,
            [KeyboardKey.Left] = ImGuiKey.LeftArrow,
            [KeyboardKey.Down] = ImGuiKey.DownArrow,
            [KeyboardKey.Up] = ImGuiKey.UpArrow,
            [KeyboardKey.PageUp] = ImGuiKey.PageUp,
            [KeyboardKey.PageDown] = ImGuiKey.PageDown,
            [KeyboardKey.Home] = ImGuiKey.Home,
            [KeyboardKey.End] = ImGuiKey.End,
            [KeyboardKey.CapsLock] = ImGuiKey.CapsLock,
            [KeyboardKey.ScrollLock] = ImGuiKey.ScrollLock,
            [KeyboardKey.NumLock] = ImGuiKey.NumLock,
            [KeyboardKey.PrintScreen] = ImGuiKey.PrintScreen,
            [KeyboardKey.Pause] = ImGuiKey.Pause,
            [KeyboardKey.F1] = ImGuiKey.F1,
            [KeyboardKey.F2] = ImGuiKey.F2,
            [KeyboardKey.F3] = ImGuiKey.F3,
            [KeyboardKey.F4] = ImGuiKey.F4,
            [KeyboardKey.F5] = ImGuiKey.F5,
            [KeyboardKey.F6] = ImGuiKey.F6,
            [KeyboardKey.F7] = ImGuiKey.F7,
            [KeyboardKey.F8] = ImGuiKey.F8,
            [KeyboardKey.F9] = ImGuiKey.F9,
            [KeyboardKey.F10] = ImGuiKey.F10,
            [KeyboardKey.F11] = ImGuiKey.F11,
            [KeyboardKey.F12] = ImGuiKey.F12,
            [KeyboardKey.LeftShift] = ImGuiKey.LeftShift,
            [KeyboardKey.LeftControl] = ImGuiKey.LeftCtrl,
            [KeyboardKey.LeftAlt] = ImGuiKey.LeftAlt,
            [KeyboardKey.LeftSuper] = ImGuiKey.LeftSuper,
            [KeyboardKey.RightShift] = ImGuiKey.RightShift,
            [KeyboardKey.RightControl] = ImGuiKey.RightCtrl,
            [KeyboardKey.RightAlt] = ImGuiKey.RightAlt,
            [KeyboardKey.RightSuper] = ImGuiKey.RightSuper,
            [KeyboardKey.KeyboardMenu] = ImGuiKey.Menu,
            [KeyboardKey.LeftBracket] = ImGuiKey.LeftBracket,
            [KeyboardKey.Backslash] = ImGuiKey.Backslash,
            [KeyboardKey.RightBracket] = ImGuiKey.RightBracket,
            [KeyboardKey.Grave] = ImGuiKey.GraveAccent,
            [KeyboardKey.Kp0] = ImGuiKey.Keypad0,
            [KeyboardKey.Kp1] = ImGuiKey.Keypad1,
            [KeyboardKey.Kp2] = ImGuiKey.Keypad2,
            [KeyboardKey.Kp3] = ImGuiKey.Keypad3,
            [KeyboardKey.Kp4] = ImGuiKey.Keypad4,
            [KeyboardKey.Kp5] = ImGuiKey.Keypad5,
            [KeyboardKey.Kp6] = ImGuiKey.Keypad6,
            [KeyboardKey.Kp7] = ImGuiKey.Keypad7,
            [KeyboardKey.Kp8] = ImGuiKey.Keypad8,
            [KeyboardKey.Kp9] = ImGuiKey.Keypad9,
            [KeyboardKey.KpDecimal] = ImGuiKey.KeypadDecimal,
            [KeyboardKey.KpDivide] = ImGuiKey.KeypadDivide,
            [KeyboardKey.KpMultiply] = ImGuiKey.KeypadMultiply,
            [KeyboardKey.KpSubtract] = ImGuiKey.KeypadSubtract,
            [KeyboardKey.KpAdd] = ImGuiKey.KeypadAdd,
            [KeyboardKey.KpEnter] = ImGuiKey.KeypadEnter,
            [KeyboardKey.KpEqual] = ImGuiKey.KeypadEqual
        };
}